default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: cards_development

test:
  <<: *default
  database: cards_test

production:
  <<: *default
  database: cards_production
  # username: cards
  # password: <%= ENV['CARDS_DATABASE_PASSWORD'] %>